services:
  giropops-senhas:
    build:
      context: ./giropops-senhas
      dockerfile: Dockerfile
    networks:
      - private-network
    environment:
      - REDIS_HOST=redis
    labels:
      com.docker.description: "Giropops Senhas App"
      com.docker.version: "1.0"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - redis

  redis:
    image: redis:8.6.1-alpine3.23
    command: redis-server --appendonly yes
    networks:
      - private-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      com.docker.description: "Redis Server"
      com.docker.version: "8.6.1-alpine3.23"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx-reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - name: server_port
        target: 443
        published: 443
        protocol: tcp
    networks:
      - private-network
      - public-network
    labels:
      com.docker.description: "Giropops Senhas Reverse Proxy"
      com.docker.version: "1.0"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    secrets:
      - tls-certificate
      - tls-key

networks:
  private-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
    labels:
      com.docker.network: "private-network"

  public-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/24"
    labels:
      com.docker.network: "public-network"

secrets:
  tls-certificate:
    file: ${SERVER_CERT_PATH}
  tls-key:
    file: ${SERVER_KEY_PATH}
